### ISSUE TITLE
Map equality testing

### ISSUE THREAD

**Issue by SoniEx2** [chris-morgan/anymap#25]
Is there any way to have AnyMapEq/AnyMapPartialEq or something?

**Comment by chris-morgan** [comment]
Sorry, not going to implement this, because it doesn’t scale, there being no generic way of doing it. `CloneAny` made it in because clone is not uncommonly desired in places that want anymap, but if you want anything else, you’ll have to implement it yourself. The bones of anymap is very straightforward, though there’s a fair bit of wrapping paper around it in anymap.
