### ISSUE TITLE
Split off TypeIdHasher into a separate crate

### ISSUE THREAD

**Issue by inodentry** [chris-morgan/anymap#33]
TypeIdHasher is useful for other abstractions dealing with dynamic typing.

I have copy-pasted that code into a private project of mine, because I wanted to use it to implement another collection type that is similar to AnyMap.

The collection I implemented seems generally-useful. It might be a good idea for me to publish it as a crate of my own (I don't think it belongs in anymap, as it is different enough from the purpose of this crate). However, to do that, I would need to duplicate the TypeIdHasher code from anymap. If we split that off into a separate crate, we could both depend on it instead of duplicating code.

**Comment by chris-morgan** [comment]
Eh, I dunno, seems a little too micro a dependency for my liking. I’m not going to extract it, and wouldn’t be inclined to use an extracted version of it unless all of these sorts of crates decided to. On the plus side, refactorings I made today lead to `TypeIdHasher` becoming part of the public API. And I changed the implementation, which you may want to look at, and if that isn’t a demonstration of why to extract things like this, I dunno what is! 😀 But I’m not doing it, because eh, zero dependencies. Probably a bad reason. *C’est la vie.*
