### ISSUE TITLE
When is the next crates.io release?

### ISSUE THREAD

**Issue by vi** [chris-morgan/anymap#37]
I see a number of commits here, but on crates.io the library is `Last Updated: 3 years ago`.

What is maintainership status of the library?

**Comment by RobbieMcKinstry** [comment]
Hi @chris-morgan! Might I suggest, if this crate is "finished" and in maintainance mode, cutting a `v1.0.0` release on crates.io?

**Comment by ruabmbua** [comment]
ping @chris-morgan especially the unreleased commit 479d756c992af132c6ba45248c65dc230c5986cf would be very helpful. Without it, there is some undefined behavior triggered by https://github.com/rust-analyzer/rust-analyzer unit tests.
The alignment of the byte array casted to `*const u64` seems to sometimes be 2 bytes, instead of 8, which fails in ptr::copy_nonoverlapping.

**Comment by chris-morgan** [comment]
anymap 1.0.0-beta.1 published finally. Some fairly significant changes, more than I expected, though external mostly very straightforward. Let me know what you reckon. I’ll leave it for a week then publish 1.0.0 if nothing seems awry.

Now to go through and close almost all the issues as resolved!

**Comment by ruabmbua** [comment]
Thank you!

**Comment by jszwedko** [comment]
Hi @chris-morgan ! Apologies to bother, just stumbling across this issue due to a reported security advisory (https://nvd.nist.gov/vuln/detail/CVE-2021-38187). Would it be reasonable to tag the beta as 1.0.0 now?

**Comment by jelmer** [comment]
Hi @chris-morgan , any chance you could submit something similar to https://github.com/rustsec/advisory-db/pull/1378 ?
